<a href="https://colab.research.google.com/github/NayloEze/Data-Types-List-and-Sets/blob/main/Numpy_x_Pandas_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

1. Create a nested list which contains the name, age and race of 10 people each. Turn this list to a dataframe.

In [2]:
#Creating a data frame from a nested list:
personal_info = [["Esther",31,"African"], ["Debra",27,"European"] ,["Minho",27,"Asian"], ["Ada", 29, "African"], ["Ben",31, "American"],
                ["Sizwe",35, "African"], ["Ethan",29, "Australian"], ["Kedi",30,"African"], ["Joong Ki", 34,"Asian"], ["Suzy",25, "American"]]
revised_info = pd.DataFrame(personal_info) 
revised_info

0   1           2
0    Esther  31     African
1     Debra  27    European
2     Minho  27       Asian
3       Ada  29     African
4       Ben  31    American
5     Sizwe  35     African
6     Ethan  29  Australian
7      Kedi  30     African
8  Joong Ki  34       Asian
9      Suzy  25    American

2. Label the columns with the appropriate column names

In [3]:
#Adding column names to the DataFrame
revised_info.columns = ["Name","Age","Race"]
revised_info

Name  Age        Race
0    Esther   31     African
1     Debra   27    European
2     Minho   27       Asian
3       Ada   29     African
4       Ben   31    American
5     Sizwe   35     African
6     Ethan   29  Australian
7      Kedi   30     African
8  Joong Ki   34       Asian
9      Suzy   25    American

3. Add a new column to your dataframe called weight and enter values for it.

In [4]:
#Adding a new column to the DataFrame
revised_info["Weight"] = [150, 165,170,145,160,175,180,173,137,120]
revised_info

Name  Age        Race  Weight
0    Esther   31     African     150
1     Debra   27    European     165
2     Minho   27       Asian     170
3       Ada   29     African     145
4       Ben   31    American     160
5     Sizwe   35     African     175
6     Ethan   29  Australian     180
7      Kedi   30     African     173
8  Joong Ki   34       Asian     137
9      Suzy   25    American     120

4. Change the name of the column for "weight" to "height". Feel free to use any method you find. 

In [5]:
#Changing the cloumn "Weight" to "Height"
revised_info_copy = revised_info.copy() # creating a new variable to contain the new dataframe with the column "Height"
revised_info_copy.rename(columns={"Weight": "Height"}, inplace=True)
print(revised_info_copy)

       Name  Age        Race  Height
0    Esther   31     African     150
1     Debra   27    European     165
2     Minho   27       Asian     170
3       Ada   29     African     145
4       Ben   31    American     160
5     Sizwe   35     African     175
6     Ethan   29  Australian     180
7      Kedi   30     African     173
8  Joong Ki   34       Asian     137
9      Suzy   25    American     120


5. Change the row index to another indexing of your choice.

In [6]:
#changing the row index to letters A - J
revised_info_copy = revised_info.copy()
revised_info_copy.rename(columns={"Weight": "Height"},index={0:"A", 1:"B",2:"C",3:"D",4:"E",5:"F",6:"G",7:"H",8:"I",9:"J"}, inplace=True)
print(revised_info_copy) 

       Name  Age        Race  Height
A    Esther   31     African     150
B     Debra   27    European     165
C     Minho   27       Asian     170
D       Ada   29     African     145
E       Ben   31    American     160
F     Sizwe   35     African     175
G     Ethan   29  Australian     180
H      Kedi   30     African     173
I  Joong Ki   34       Asian     137
J      Suzy   25    American     120


6. Select/display only the age and race columns

In [7]:
#using the double bracket method to index 
revised_info_copy[["Age","Race"]]

Age        Race
A   31     African
B   27    European
C   27       Asian
D   29     African
E   31    American
F   35     African
G   29  Australian
H   30     African
I   34       Asian
J   25    American

7. Select/display the first five names and their age 

In [8]:
#using the.loc method to display rhe fist five names and thier ages within the DataFrame
revised_info_copy.loc["A":"E","Name":"Age"]

Name  Age
A  Esther   31
B   Debra   27
C   Minho   27
D     Ada   29
E     Ben   31

8. Select all rows but only the third column

In [9]:
#using the .iloc method to display all rows but only the third column which is "Race"
revised_info_copy.iloc[0:9,2:3]

Race
A     African
B    European
C       Asian
D     African
E    American
F     African
G  Australian
H     African
I       Asian

9. Write some code to return the row index back to the default numbering before it was changed. Use your researching skills.

In [10]:
#Returning the index to its original numbering
final_copy = revised_info_copy.reset_index(drop = True) #drop takes out the new index A-J
final_copy

Name  Age        Race  Height
0    Esther   31     African     150
1     Debra   27    European     165
2     Minho   27       Asian     170
3       Ada   29     African     145
4       Ben   31    American     160
5     Sizwe   35     African     175
6     Ethan   29  Australian     180
7      Kedi   30     African     173
8  Joong Ki   34       Asian     137
9      Suzy   25    American     120

10. Create a dataframe from the dictionary above. Using the dataframe, select books with ratings not less than 200000

In [11]:
#creating a DataFrame from the dictionary provided.
chimamanda = {"Books":["Americanah", "Half of a Yellow Sun", "Purple Hibiscus",
                    "The Thing Around Your Neck", "We Should All Be Feminists"], 
             "Ratings":[297972, 120131, 5116, 32064, 204882]}
chimamandabooks = pd.DataFrame(chimamanda)
chimamandabooks

Books  Ratings
0                  Americanah   297972
1        Half of a Yellow Sun   120131
2             Purple Hibiscus     5116
3  The Thing Around Your Neck    32064
4  We Should All Be Feminists   204882

In [12]:
#To select books whose ratings are greater than 200,000
chimamandabooks[chimamandabooks.Ratings >= 200000]

Books  Ratings
0                  Americanah   297972
4  We Should All Be Feminists   204882

11. Create a numpy array with data type boolean

In [13]:
#creating a numpy array with boolean data type 
arr = np.array([True,False,True,False])
print(arr)
print("This datatype is a ",arr.dtype)
print("The shape of this datatype is a ",arr.shape)

[ True False  True False]
This datatype is a  bool
The shape of this datatype is a  (4,)


In [14]:
# 12. Convert the following array to an integer

a = np.array([[True, False, False],
              [True, True, True],
              [False, False, False]])

p = a.astype(int)

print(p)
print("The shape of the p is",p.shape)

[[1 0 0]
 [1 1 1]
 [0 0 0]]
The shape of the p is (3, 3)


In [15]:
#13. Stack these numpy arrays - vertically and horizontally

a = np.array([[7, 8, 9],
              [10, 11, 12]])

aa = np.array([[1, 2, 3],
               [4, 5, 6]])

v = np.hstack([a, aa]) #using hstack
w = np.vstack([a, aa]) #using vstack
print(v)
print(w)

[[ 7  8  9  1  2  3]
 [10 11 12  4  5  6]]
[[ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


14. Create 2 3D arrays, add them together to create a new array, then sort the new array.

In [16]:
#adding 3D arrays using the add method 
arr =np.array([[[1,5,3],[4,11,6]],[[23,8,9],[12,11,18]]])
arr2 =np.array([[[2,7,6],[8,17,12]],[[20,16,18],[23,22,24]]])

arr3 = np.add(arr,arr2)

print(arr3)
print("The shape of the arr3 is",arr3.shape)


[[[ 3 12  9]
  [12 28 18]]

 [[43 24 27]
  [35 33 42]]]
The shape of the arr3 is (2, 2, 3)


In [17]:
#sort arr3
print(np.sort(arr3))
print("The shape of the arr3 is",arr3.shape)

[[[ 3  9 12]
  [12 18 28]]

 [[24 27 43]
  [33 35 42]]]
The shape of the arr3 is (2, 2, 3)


In [18]:
#15. Using step slicing, slice the array below from any position using 3 steps

a = np.array([5, 8, 7, 1, 0, 9, 4, 2, 6, 3])
print("Taking 3 steps, we have these numbers",a[0:9:3], "between the first and last element of the variable a.")


Taking 3 steps, we have these numbers [5 1 4] between the first and last element of the variable a.
